export enum Entities {
  Role = 'Role',
  Permission = 'Permission',
  User = 'User',
  Photo = 'Photo',
  Admin = 'Admin',
  Employee = 'Employee',
  Chat = 'Chat',
  Message = 'Message',
  City = 'City',
  Payment = 'Payment',
  Driver = 'Driver',
  Profit = 'Profit',
  Statistics = 'Statistics',
  Wallet = 'Wallet',
  All = 'all',
}
