export enum Entities {
  Order = 'Order',
  Suborder = 'Suborder',
  Role = 'Role',
  Permission = 'Permission',
  User = 'User',
  Photo = 'Photo',
  Admin = 'Admin',
  Employee = 'Employee',
  Message = 'Message',
  City = 'City',
  Payment = 'Payment',
  Driver = 'Driver',
  Car = 'Car',
  Profit = 'Profit',
  Advantage = 'Advantage',
  Statistics = 'Statistics',
  Setting = 'Setting',
  Wallet = 'Wallet',
  All = 'all',
}
