export enum Entities {
  Product = 'Product',
  Role = 'Role',
  Permission = 'Permission',
  User = 'User',
  Photo = 'Photo',
  Admin = 'Admin',
  Employee = 'Employee',
  Comment = 'Comment',
  Chat = 'Chat',
  Message = 'Message',
  Category = 'Category',
  City = 'City',
  Store = 'Store',
  Payment = 'Payment',
  Delivery = 'Delivery',
  Coupon = 'Coupon',
  Profit = 'Profit',
  Statistics = 'Statistics',
  Wallet = 'Wallet',
  All = 'all',
}
