export enum GROUPS {
  ALL_ROLES = 'group_all_roles',
  ROLE = 'group_role_details',
  ALL_PERMISSIONS = 'group_all_permissions',
  PERMISSION = 'group_permission_details',
  ALL_USERS = 'group_all_users',
  USER = 'group_user_details',
  ALL_ADMINS = 'group_all_admins',
  ADMIN = 'group_admin_details',
  ALL_EMPLOYEES = 'group_all_employees',
  EMPLOYEE = 'group_employee_details',
  ALL_DRIVERS = 'group_all_drivers',
  DRIVER = 'group_driver_details',
  ALL_CARS = 'group_all_cars',
  CAR = 'group_car_details',
  ALL_ORDERS = 'group_all_orders',
  ORDER = 'group_order_details',
  ALL_ADVANTAGES = 'group_all_advantages',
  ADVANTAGE = 'group_advantage_details',
}
