export enum GROUPS {
  ALL_ROLES = 'group_all_roles',
  ROLE = 'group_role_details',
  ALL_PERMISSIONS = 'group_all_permissions',
  PERMISSION = 'group_permission_details',
  ALL_USERS = 'group_all_users',
  USER = 'group_user_details',
  ALL_ADMINS = 'group_all_admins',
  ADMIN = 'group_admin_details',
  ALL_EMPLOYEES = 'group_all_employees',
  EMPLOYEE = 'group_employee_details',
  ALL_PRODUCTS = 'group_all_products',
  PRODUCT = 'group_product_details',
  ALL_COMMENTS = 'group_all_comments',
  COMMENT = 'group_comment_details',
}
