name: naqla_driver
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependency_overrides:
  win32: ^5.5.4

flutter_gen:
  output: lib/generated/flutter_gen/
  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #? common state
  common_state:
    path: packages/common_state

  #?state management
  flutter_bloc: ^8.1.6
  dio: ^5.7.0

  #?UI
  flutter_screenutil: ^5.9.3
  text_scroll: ^0.2.0
  pinput: ^5.0.0
  dropdown_button2: ^2.3.9
  fluttertoast: ^8.2.10
  flutter_form_builder: ^9.7.0
  form_builder_validators: ^11.1.1
  flutter_keyboard_visibility: ^6.0.0
  flutter_spinkit: ^5.2.1
  iconly: ^1.0.1
  flutter_colorpicker: ^1.1.0
  modal_bottom_sheet: ^3.0.0
  badges: ^3.1.2

  #?image
  image_picker: ^1.1.2
  flutter_svg: ^2.0.16
  image_cropper: ^8.1.0
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  uuid: ^4.5.1
  http_parser: ^4.1.2
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1

  intl: ^0.19.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  logger: ^2.5.0
  shared_preferences: ^2.3.5

  #?router
  go_router: ^14.6.2

  #?location:
  google_maps_flutter: ^2.10.0

  #?realTme
  socket_io_client: ^3.0.2


  flutter_localizations:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/jpg/logo.jpg"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.8.0
  build_runner: ^2.4.14
  injectable_generator: ^2.6.2

flutter:

  uses-material-design: true
#  generate: true

  assets:
    - assets/images/svg/
    - assets/images/jpg/
    - assets/icons/essential/
    - assets/icons/png/
    - assets/icons/arrow/
    - assets/icons/flags/

  fonts:
    - family: noor
      fonts:
        - asset: assets/fonts/ArbFONTS-AGCRegular.ttf

flutter_intl:
  enabled: true

