import { NavigationBar } from "@/components/layouts/navigation-bar";
import { Providers } from "@/components/providers";
import { cn } from "@/lib/utils";
import { dir } from "i18next";
import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "../globals.css";
import { PageProps } from "../type";

const cairo = Cairo({ subsets: ["arabic", "latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { lng },
}: {
  children: React.ReactNode;
} & PageProps) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body
        className={cn(
          "flex",
          dir(lng) === "ltr" ? "[&_*]:dir-ltr" : "[&_*]:dir-rtl",
          cairo.className,
        )}
      >
        <Providers>
          <NavigationBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
