import { Providers } from "@/components/providers";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import { dir } from "i18next";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { LayoutProps } from "../type";

const rubik = localFont({ src: "../../public/Rubik-VariableFont_wght.ttf" });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children, params: { lng } }: LayoutProps) {

  return (
    <html
      lang={lng}
      dir={dir(lng)}
      className="flex min-h-screen flex-col"
      suppressHydrationWarning
    >
      <body
        className={cn(
          "flex flex-1 flex-col",
          dir(lng) === "ltr" ? "[&_*]:dir-ltr" : "[&_*]:dir-rtl",
          rubik.className,
        )}
      >
        <Providers>
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
