name: naqla
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.0-229.0.dev <4.0.0'

flutter_gen:
  output: lib/generated/flutter_gen/
  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0

  #UI
  auto_size_text: ^3.0.0
  text_scroll: ^0.2.0
  pinput: ^3.0.1
  dropdown_button2: ^2.3.9
  awesome_dialog: ^3.2.0
  fluttertoast: ^8.2.2
  flutter_form_builder: ^9.1.1
  flutter_keyboard_visibility: ^6.0.0
  flutter_screenutil: ^5.9.0
  lottie: ^2.7.0
  just_the_tooltip: ^0.0.12
  infinite_scroll_pagination: ^4.0.0
  flutter_spinkit: ^5.2.0

  #IMAGE:
  flutter_blurhash: ^0.8.2
  image_picker: ^1.0.5
  flutter_svg: ^2.0.6
  image_cropper: ^5.0.1
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.2
  uuid: ^4.3.3
  http_parser: ^4.0.2

  #State management
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  dio: ^5.1.2
  form_builder_validators: ^9.0.0
  intl: ^0.18.1
  get_it: ^7.6.0

  injectable: ^2.3.0
  internet_connection_checker: any
  logger: ^2.0.2+1
  shared_preferences: ^2.2.2

  #router
  go_router: ^13.0.0

  #map
  location: ^5.0.3
  google_maps_flutter: ^2.5.0
  flutter_polyline_points: ^2.0.0
  


  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_gen_runner: ^5.3.2
  build_runner: ^2.4.4
  injectable_generator: ^2.1.5



flutter:
  uses-material-design: true
#  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/svg/
    - assets/images/jpg/
    - assets/lottie/
    - assets/icons/essential/
    - assets/icons/arrow/
    - assets/icons/social/
    - assets/icons/flags/


  fonts:
    - family: noor
      fonts:
        - asset: assets/fonts/ArbFONTS-AGCRegular.ttf

flutter_intl:
  enabled: true
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
